name: testing new metrics

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: request updated metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # output_action none stops the autocommit bs
          output_action: none
          filename: metrics.svg

          # metadata
          user: gamerjamer43
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York

          # plugin options
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css, javascript, python, makefile
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_stars: yes
          plugin_stars_limit: 4

      - name: move copy over
        run: |
          mkdir -p public
          cp metrics.svg public/metrics.svg

      - name: setup pages
        uses: actions/configure-pages@v5

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: update on github pages
        id: deployment
        uses: actions/deploy-pages@v4
